### ISSUE TITLE
Is section 3.2 needed as written?

### ISSUE THREAD

**Issue by iannevans** [ivoa/HighEnergyDataNote#25]
I still need to re-read the entire HEIG draft note, but I think section 3.2 may be unnecessary as written.

The workflow described in section 3.2.1 is no different than the data selection step that is also done at every other wavelength.  Almost always an observation will include data that are not relevant to the analysis task at hand and removing the additional data is usually necessary as they can adversely affect the analysis (e.g., by adding background).

The content of 3.2.2 is very relevant, but given it is “… one of the main driver[s] for enabling …” I would suggest that this paragraph be fleshed out a little more and inserted earlier in the document, certainly no later than section 3.1 and possibly even in the section 1 introduction.  I can take a crack at updating 3.2.2 if you'd like to go down this path ...

**Comment by mservillat** [comment]
Looking back at the history of the document, it was proposed at one point to add more structure to section 3, which contained a list of topics quite specific to HE (but maybe also found in other domain), hence the "data flow" and "work flow section", but you are right that they are not really relevant anymore, as 3.2.2 became a larger topic indeed, not yet reflected in the note. As such, it should indeed appear somewhere in section 1.

I would suggest first to change 3.1 to "Data specificities", as this is a description of the data. Then, 3.2 should be "Assumptions and probabilistic approach" or rephrased in some better way. I tend to think that the HE data description has to come first (3.1), so that in the next section we can build on it and better emphasize the fact that we often deal with low count statistic, that filtering of events may be tricky, that assumptions appear at various steps in the data processing. Finally there is the unfolding problem (you will explain this better than me).

A quick search led me to this reference, but there may be many others : 
https://www.frontiersin.org/journals/astronomy-and-space-sciences/articles/10.3389/fspas.2023.1228508/full 

Could this be a better structure : 
3.2 Statistical challenges
  3.2.1 Low count statistics
  3.2.2 Event selection
  3.2.3 Event binning
  3.2.4 The unfolding problem
(This may comes differently once written down)

**Comment by mservillat** [comment]
Section 3.2 rewritten in #33
